# Generated by Django 4.2.4 on 2023-08-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplicacion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuarios",
            name="password_usuarios",
            field=models.CharField(default="password", max_length=15),
        ),
        migrations.AddField(
            model_name="usuarios",
            name="user_usuarios",
            field=models.CharField(default="usuario", max_length=15),
        ),
    ]
