# Generated by Django 4.2.4 on 2023-08-15 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aplicacion", "0002_usuarios_password_usuarios_usuarios_user_usuarios"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuarios",
            old_name="correo",
            new_name="correo_usuarios",
        ),
        migrations.RemoveField(
            model_name="usuarios",
            name="apellidos",
        ),
        migrations.RemoveField(
            model_name="usuarios",
            name="nombre",
        ),
        migrations.RemoveField(
            model_name="usuarios",
            name="user_usuarios",
        ),
    ]
